update

diff --git a/f-ext b/f-ext
--- a/f-ext
+++ b/f-ext
@@ -5,28 +5,31 @@ usage() {
     echo "Find files by extension"
 }
 
-f-ext() {
-    printf "File extension: "
-    read ext
+printf "File extension: "
+read ext
 
-    if [ -z "$ext" ]; then
-        usage
-        return 1
-    fi
+if [ -z "$ext" ]; then
+    usage
+    return 1
+fi
 
-    file=$(find / -type f -iname "*.$ext" 2>/dev/null | fzf-tmux -p --reverse --preview 'file {} && (bat --style=plain --color=always {} || head -n 100 {})')
+file=$(find / -type f -iname "*.$ext" 2>/dev/null | fzf-tmux -p --reverse --exact --preview '
+  case $(file --mime-type -b {}) in
+    text/*) bat --style=plain --color=always {} || head -n 100 {} ;;
+    application/pdf) pdftotext {} - || echo "Cannot preview PDF, but will open with xpdf" ;;
+    image/*) exiftool {} || echo "Cannot preview image metadata" ;;
+    *) file {} ;;
+  esac')
 
-    case "$ext" in
-        pdf)
-            xpdf "$file" ;;
-        png|jpg|jpeg|gif|bmp|svg)
-            xdg-open "$file" ;;
-        txt|md|log|c|cpp|h|py|sh)
-            vim "$file" ;;
-        *)
-            echo "No designated handler for .$ext files, attempting xdg-open."
-            xdg-open "$file" ;;
-    esac
-}
-
+case "$ext" in
+    pdf)
+        xpdf "$file" ;;
+    png|jpg|jpeg|gif|bmp|svg)
+        xdg-open "$file" ;;
+    txt|md|log|c|cpp|h|rs|hs|go|py|sh|ts|js|html|css)
+        vim "$file" ;;
+    *)
+        echo "No designated handler for .$ext files, attempting xdg-open."
+        xdg-open "$file" ;;
+esac
 
